---
apiVersion: v1
kind: Service
metadata:
  name: hysteron-keeper
spec:
  selector:
    app.kubernetes.io/app: hysteron-second

---
apiVersion: v1
kind: Service
metadata:
  name: hysteron-sentinel
spec:
  selector:
    app.kubernetes.io/app: hysteron-second

---
apiVersion: v1
kind: Service
metadata:
  name: hysteron-proxy
spec:
  selector:
    app.kubernetes.io/app: hysteron-second
