---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common
  - keeper
  - sentinel
  - proxy

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: hysteron
