apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hysteron-keeper
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/app: hysteron
                    app.kubernetes.io/component: keeper
