---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - state-secret.yaml
  - job-initialize.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml

configMapGenerator:
  - name: hysteron-common-env
    literals:
      - HYSTERON_CLUSTER_NAME=kube-hysteron
      - HYSTERON_K8S_RESOURCE_NAME=hysteron-state
    options:
      disableNameSuffixHash: true
      immutable: true
  - name: hysteron-initialize-spec
    files:
      - cluster-spec.json
    options:
      disableNameSuffixHash: true
      immutable: true

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: keeper
