---
apiVersion: v1
kind: Service
metadata:
  name: hysteron-ro
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: hysteron-rw
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
