---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml

configMapGenerator:
  - name: hysteron-sentinel-env
    envs:
      - sentinel.env

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: sentinel
