---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hysteron-keeper
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: keeper

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hysteron-sentinel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: sentinel
