---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - sts.yaml

configMapGenerator:
  - name: hysteron-keeper-env
    envs:
      - keeper.env

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: keeper
