---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - pdb.yaml
  - sts.yaml

configMapGenerator:
  - name: hysteron-keeper-env
    envs:
      - keeper.env

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/app: hysteron
      app.kubernetes.io/component: keeper

replacements:
  - source:
      kind: StatefulSet
      name: hysteron-keeper
      fieldPath: spec.selector
    targets:
      - select:
          kind: PodDisruptionBudget
          name: hysteron-keeper
        fieldPaths:
          - spec.selector
        options:
          create: true
  - source:
      kind: StatefulSet
      name: hysteron-keeper
      fieldPath: spec.selector.matchLabels
    targets:
      - select:
          kind: StatefulSet
          name: hysteron-keeper
        fieldPaths:
          - spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.0.podAffinityTerm.labelSelector.matchLabels
        options:
          create: true
