---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hysteron-keeper
spec:
  replicas: 3
  serviceName: hysteron-keeper
  template:
    spec:
      serviceAccountName: hysteron
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000

      containers:
        - name: keeper
          image: docker.io/woozymasta/hysteron-pg:latest
          command:
            - /bin/hysteron
            - keeper
            - kubernetes

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi

          envFrom:
            - configMapRef:
                name: hysteron-common-env
            - configMapRef:
                name: hysteron-keeper-env
            - secretRef:
                name: hysteron
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          ports:
            - name: postgres
              containerPort: 5432
            - name: metrics
              containerPort: 9108
            - name: health
              containerPort: 8081

          startupProbe:
            httpGet:
              path: /health/startup
              port: health
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health/live
              port: health
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
            # Optional alternative:
            # tcpSocket:
            #   port: postgres
          readinessProbe:
            httpGet:
              path: /health/ready
              port: health
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
            # Optional alternative:
            # tcpSocket:
            #   port: postgres

          volumeMounts:
            - name: data
              mountPath: /var/lib/hysteron/data
      volumes:
        - name: data
          emptyDir: {}
