global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: hysteron-sentinel
    static_configs:
      - targets:
          - sentinel1:9108
          - sentinel2:9108
  - job_name: hysteron-keeper
    static_configs:
      - targets:
          - keeper-a-1:9108
          - keeper-a-2:9108
          - keeper-b-1:9108
          - keeper-b-2:9108
  - job_name: hysteron-proxy
    static_configs:
      - targets:
          - proxy-a-1:9108
          - proxy-a-2:9108
          - proxy-b-1:9108
