apiVersion: apps/v1
kind: Deployment
metadata:
  name: hysteron-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: hysteron-proxy
      hysteron-cluster: kube-hysteron
  template:
    metadata:
      labels:
        component: hysteron-proxy
        hysteron-cluster: kube-hysteron
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: hysteron-proxy
          image: sorintlab/hysteron:master-pg10
          command:
            - "/bin/bash"
            - "-ec"
            - |
              exec gosu hysteron hysteron proxy kubernetes -- --listen-address 0.0.0.0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HYSTERON_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['hysteron-cluster']
            - name: HYSTERON_K8S_RESOURCE_KIND
              value: "configmap"
            - name: HYSTERON_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            ## Uncomment this to enable debug logs
            #- name: HYSTERON_DEBUG
            #  value: "true"
          ports:
            - containerPort: 5432
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5

