apiVersion: v1
kind: Service
metadata:
  name: hysteron-proxy-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    component: hysteron-proxy
    hysteron-cluster: kube-hysteron

